// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARyyrJkogPjMuAgYH8SvRCUkv3oe_lD7Q',
    appId: '1:128272551036:web:3afc74181339d5345ecdf9',
    messagingSenderId: '128272551036',
    projectId: 'ecogo-booking',
    authDomain: 'ecogo-booking.firebaseapp.com',
    storageBucket: 'ecogo-booking.firebasestorage.app',
    measurementId: 'G-JRQNRKYP7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYG6LpsqHa5cj2-lQ_HDKAWtvkzeFng5c',
    appId: '1:128272551036:android:665a0c9bd7b564725ecdf9',
    messagingSenderId: '128272551036',
    projectId: 'ecogo-booking',
    storageBucket: 'ecogo-booking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4A4KxqAOVB8k-esm_R4viiZ5Y8prhKnQ',
    appId: '1:128272551036:ios:0603c248ea1757565ecdf9',
    messagingSenderId: '128272551036',
    projectId: 'ecogo-booking',
    storageBucket: 'ecogo-booking.firebasestorage.app',
    iosBundleId: 'com.example.ecogoBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4A4KxqAOVB8k-esm_R4viiZ5Y8prhKnQ',
    appId: '1:128272551036:ios:0603c248ea1757565ecdf9',
    messagingSenderId: '128272551036',
    projectId: 'ecogo-booking',
    storageBucket: 'ecogo-booking.firebasestorage.app',
    iosBundleId: 'com.example.ecogoBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARyyrJkogPjMuAgYH8SvRCUkv3oe_lD7Q',
    appId: '1:128272551036:web:adacb6d3e1f468c65ecdf9',
    messagingSenderId: '128272551036',
    projectId: 'ecogo-booking',
    authDomain: 'ecogo-booking.firebaseapp.com',
    storageBucket: 'ecogo-booking.firebasestorage.app',
    measurementId: 'G-HZT3Q31EDZ',
  );
}
